dependencies {
    api(libs.kumaFabric)
    include(libs.kumaFabric)
    compileOnly libs.modMenu
    compileOnly libs.jeiCommon
    compileOnly libs.wthitFabric
    compileOnly libs.jadeFabric
    // compileOnly libs.trinkets
    compileOnly libs.fabricPermissionsApi
    compileOnly libs.rebornEnergy
    compileOnly libs.clothConfigFabric
    compileOnly libs.configuredFabric
}