dependencies {
    include modApi(libs.kumaFabric.get())
    modCompileOnly libs.modMenu
    modCompileOnly libs.jeiCommon
    modCompileOnly libs.wthitFabric
    modCompileOnly libs.jadeFabric
    modCompileOnly libs.trinkets
    modCompileOnly libs.fabricPermissionsApi
    modCompileOnly libs.rebornEnergy
    modCompileOnly libs.clothConfigFabric
    modCompileOnly libs.configuredFabric
}