# Mod
mod_id = balm
mod_name = Balm
mod_author = BlayTheNinth
credits = BlayTheNinth
description = Abstraction Layer (but not really) for Blay's multiplatform mods
version = 21.11.2
group = net.blay09.mods
homepage=https://mods.twelveiterations.com/minecraft/balm
sources=https://github.com/TwelveIterationMods/Balm
issues=https://github.com/TwelveIterationMods/Balm/issues
discord = https://discord.gg/VAfZ2Nau6j
license = All Rights Reserved

# Publishing
curseforge_project_id = 531761
modrinth_project_id = MBAkmtvl
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Minecraft
java_version = 21

# NeoForge
neoforge_snapshot_url = 

# Dependencies
kuma_version_range = [21.11,21.12)

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
