# Mod
mod_id = balm
mod_name = Balm
mod_author = BlayTheNinth
credits = BlayTheNinth
description = Abstraction Layer (but not really) for Blay's multiplatform mods
version = 21.10.5
group = net.blay09.mods
homepage=https://mods.twelveiterations.com/minecraft/balm
sources=https://github.com/TwelveIterationMods/Balm
issues=https://github.com/TwelveIterationMods/Balm/issues
discord = https://discord.gg/VAfZ2Nau6j
license = All Rights Reserved

# Publishing
curseforge_project_id = 531761
modrinth_project_id = MBAkmtvl
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Minecraft
minecraft_version = 1.21.10
minecraft_versions = 1.21.10
minecraft_version_range = [1.21.10,)
java_version = 21

# NeoForm and Parchment
neo_form_version = 1.21.10-20251007.142004
parchment_minecraft = 1.21.9
parchment_version = 2025.10.05

# Forge
forge_version = 60.0.0
forge_version_range = [60,)
forge_loader_version_range = [60,)

# NeoForge
neoforge_snapshot_url = 
neoforge_version = 21.10.38-beta
neoforge_version_range = [21,)
neoforge_loader_version_range = [1,)

# Fabric
fabric_version = 0.135.0+1.21.10
fabric_loader_version = 0.17.2

# Dependencies
kuma_version = 21.10.4+1.21.10
kuma_version_range = [21.10,21.11)
jei_minecraft_version = 1.19.2
jei_version = 11.4.0.288
rei_version = 10.0.581
mixin_version = 0.8.5
modmenu_version = 14.0.0-rc.2
wthit_version=16.0.1
jade_fabric_version=6906804
jade_neoforge_version=6170888
theoneprobe_version=6106998

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false

pack_format_number = 71