[versions]
minecraft = "26.1-snapshot-3"
neoForm = "26.1-snapshot-3-1"
neoForge = "26.1.0.0-alpha.6+snapshot-2"
forge = "61.0.1"
fabricApi = "0.142.0+26.1"
fabricLoader = "0.18.4"
kuma = "26.1.0.1-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.21.10", version = "2025.10.12" }

neoForm = { module = "net.neoforged:neoform", version.ref = "neoForm" }
neoForge = { module = "net.neoforged:neoforge", version.ref = "neoForge" }
forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }

kumaCommon = { module = "net.blay09.mods:kuma-api-common", version.ref = "kuma" }
kumaFabric = { module = "net.blay09.mods:kuma-api-fabric", version.ref = "kuma" }
kumaNeoForge = { module = "net.blay09.mods:kuma-api-neoforge", version.ref = "kuma" }
kumaForge = { module = "net.blay09.mods:kuma-api-forge", version.ref = "kuma" }

mixin = { module = "org.spongepowered:mixin", version = "0.8.7" }
mixinExtras = { module = "io.github.llamalad7:mixinextras-common", version = "0.5.2" }

wthitCommon = { module = "mcp.mobius.waila:wthit-api", version = "mojmap-16.0.1" }
wthitFabric = { module = "mcp.mobius.waila:wthit", version = "fabric-16.0.1" }
wthitNeoForge = { module = "mcp.mobius.waila:wthit", version = "neo-16.0.1" }
wthitForge = { module = "mcp.mobius.waila:wthit", version = "forge-16.0.1" }
jeiCommon = { module = "mezz.jei:jei-1.21.11-common-api", version = "27.3.0.14" }
modMenu = { module = "maven.modrinth:modmenu", version = "15.0.0" }
trinkets = { module = "dev.emi:trinkets", version = "3.10.0" }
fabricPermissionsApi = { module = "me.lucko:fabric-permissions-api", version = "0.4.0" }
rebornEnergy = { module = "teamreborn:energy", version = "4.2.0" }
clothConfigFabric = { module = "me.shedaniel.cloth:cloth-config-fabric", version = "19.0.147" }
configuredFabric = { module = "curse.maven:configured-457570", version = "6802489" }
jadeFabric = { module = "maven.modrinth:jade", version = "21.0.1+fabric" }
jadeNeoForge = { module = "maven.modrinth:jade", version = "21.0.1+neoforge" }
curios = { module = "top.theillusivec4.curios:curios-neoforge", version = "9.5.1+1.21.1" }
theOneProbe = { module = "curse.maven:the-one-probe-245211", version = "6106996" }

[plugins]
fabricLoom = { id = "net.fabricmc.fabric-loom", version = "1.14-SNAPSHOT" }
modDevGradle = { id = "net.neoforged.moddev", version = "2.0.139" }
forgeGradle = { id = "net.minecraftforge.gradle", version = "[7,8)" }
forgeJarJar = { id = "net.minecraftforge.jarjar", version = "0.2.3" }
mixin = { id = "org.spongepowered.mixin", version = "0.7-SNAPSHOT" }
curseForgeGradle = { id = "net.darkhax.curseforgegradle", version = "1.1.26" }
modrinthMinotaur = { id = "com.modrinth.minotaur", version = "2.+" }
