modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/TwelveIterations/Balm/issues"
[[mods]]
modId="balm_example"
version="1.0"
displayName="Balm Example Mod"
displayURL="https://balm.twelveiterations.com/"
logoFile="balm.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''An example mod for Balm.'''
