dependencies {
    jarJar(group: "net.blay09.mods", name: "kuma-api-forge", version: "$kuma_version") {
        transitive = false
    }
    compileOnly("mezz.jei:jei-$jei_minecraft_version-common-api:$jei_version")
    if (jei_minecraft_version == minecraft_version) {
        runtimeOnly("mezz.jei:jei-$jei_minecraft_version-forge:$jei_version")
    }

    // temporary hacky fix as suggested by Forge
    implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }

    compileOnly("top.theillusivec4.curios:curios-forge:5.11.1+1.20.1:api")
    compileOnly fg.deobf("mcp.mobius.waila:wthit:forge-$wthit_version")
}