dependencies {
    api libs.kumaCommon
    compileOnly libs.wthitCommon
    compileOnly libs.jeiCommon
    compileOnly libs.mixinExtras
    compileOnly libs.jadeNeoForge
    compileOnly libs.trinketsUpdated
    compileOnly libs.clothConfigNeoForge
    compileOnly libs.configuredNeoForge
    compileOnly libs.ftbUltimineCommon
    compileOnly libs.vivecraftCommon
}
