modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="https://github.com/TwelveIterations/Balm/issues"
[[mods]]
modId="balm"
version="${version}"
displayName="${mod_name}"
displayURL="https://balm.twelveiterations.com/"
logoFile="balm.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[mixins]]
config = "balm.mixins.json"
[[mixins]]
config = "balm.api.mixins.json"
[[mixins]]
config = "balm.neoforge.mixins.json"
[[dependencies.balm]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.balm]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"
