dependencies {
    compileOnly "net.blay09.mods:kuma-api-neoforge:$kuma_version"
    jarJar("net.blay09.mods:kuma-api-neoforge") {
        version {
            strictly kuma_version_range
            prefer kuma_version
        }
    }
    compileOnly "mezz.jei:jei-$jei_minecraft_version-common-api:$jei_version"
    compileOnly("top.theillusivec4.curios:curios-neoforge:9.2.2+1.21.1:api")
    compileOnly("curse.maven:jade-324717:$jade_neoforge_version")
    compileOnly("mcp.mobius.waila:wthit:neo-$wthit_version")
    compileOnly("curse.maven:the-one-probe-245211:6106996")
}